sudo: required
dist: trusty

language: rust

rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: stable
    - rust: beta

before_script:
  - sudo apt-get -qq update
  - sudo apt-get -y install libtool autoconf libpcap-dev sqlite3 libsqlite3-dev
  - libtoolize
  - autoreconf -i
  - ./configure
# See https://github.com/travis-ci/travis-ci/issues/1350
  - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers

script:
  - cargo build --verbose
  - sudo cargo test --verbose
