sudo: required
dist: trusty

language: rust

rust:
  - nightly
  - beta
  - stable

before_script:
  - sudo apt-get -qq update
  - sudo apt-get -y install libtool autoconf libpcap-dev sqlite3 libsqlite3-dev
  - libtoolize
  - autoreconf -i
  - ./configure
