sudo: required
dist: trusty

language: rust

rust:
  - nightly
  - beta
  - stable

cache: cargo

before_script:
  - sudo apt-get -qq update
  - sudo apt-get -y install libpcap-dev sqlite3 libsqlite3-dev
# See https://github.com/travis-ci/travis-ci/issues/1350
  - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers

script:
  - cargo build --verbose
  - sudo TEST_INF=eth0 TEST_SRCIP=$(sh ./ip.sh) RUST_LOG=carp RUST_BACKTRACE=1 cargo test --verbose -- --nocapture
