[package]
name = "carp"
version = "0.1.0"
authors = ["Herman J. Radtke III <herman@hermanradtke.com>"]

build = "build.rs"

[dependencies]
libc = "0.2.7"
nix = "0.4.2"

[build-dependencies]
gcc = "0.3"
